CREATE TABLE notification (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    email_sent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);