{
 "title": "Главный дашборд",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Системные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Статус сервисов",
   "type": "stat",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"front\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"account\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"cash\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"transfer\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"notification\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"blocker\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"exchange\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"generator\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"front\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "system_cpu_usage{job=\"account\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "system_cpu_usage{job=\"cash\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "system_cpu_usage{job=\"transfer\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "system_cpu_usage{job=\"notification\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "system_cpu_usage{job=\"blocker\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "system_cpu_usage{job=\"exchange\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "system_cpu_usage{job=\"generator\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Бизнес метрики",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "Количество логинов за 30 минут",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (login) (increase(success_login_total[30m]))",
     "legendFormat": "Succes: {{login}}"
    },
    {
     "expr": "sum by (login) (increase(failed_login_total[30m]))",
     "legendFormat": "Failed: {{login}}"
    }
   ]
  },
  {
   "title": "Ошибки при работе со своими счетами",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (login) (increase(failed_change_account_balance_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибки переводов межу счетами",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (login_from,login_to) (increase(failed_transfer_total[5m]))",
     "legendFormat": "{{login_from}} to {{login_to}}"
    }
   ]
  }
 ]
}